#!/bin/sh
# postinst script for kompas

set -e

update-alternatives --install /usr/bin/gstreamer-codec-install \
		    gstreamer-codec-install \
		    /usr/bin/kompas 90 || true

#DEBHELPER#

exit 0

