#!/bin/sh
# prerm script for kompas

set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
	update-alternatives --remove gstreamer-codec-install \
			    /usr/bin/kompas || true

fi

#DEBHELPER#

exit 0

