// From https://specifications.freedesktop.org/menu-spec/latest/apa.html
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Category {
    AudioVideo,
    Development,
    Education,
    Game,
    Graphics,
    Network,
    Office,
    Science,
    Settings,
    System,
    Utility,
    CosmicApplet,
    ActionGame,
    AdventureGame,
    ArcadeGame,
    BoardGame,
    CardGame,
    LogicGame,
    RolePlaying,
    Shooter,
    Simulation,
    SportsGame,
    StrategyGame,
    Emulator,
    Photography,
    RasterGraphics,
    VectorGraphics,
    ThreeDGraphics,
    Audio,
    Video,
    AudioVideoEditing,
    Player,
    Recorder,
    WebBrowser,
    Email,
    Chat,
    FileTransfer,
    Spreadsheet,
    WordProcessor,
    Presentation,
    Calendar,
    Finance,
    Ide,
    TextEditor,
    Debugger,
    Database,
    WebDevelopment,
    Math,
    Languages,
    Geography,
    Astronomy,
    FileManager,
    Archiving,
    Security,
    Monitor,
}

impl Category {
    pub fn id(&self) -> &'static str {
        match self {
            Self::AudioVideo => "AudioVideo",
            Self::Development => "Development",
            Self::Education => "Education",
            Self::Game => "Game",
            Self::Graphics => "Graphics",
            Self::Network => "Network",
            Self::Office => "Office",
            Self::Science => "Science",
            Self::Settings => "Settings",
            Self::System => "System",
            Self::Utility => "Utility",
            Self::CosmicApplet => "CosmicApplet",
            Self::ActionGame => "ActionGame",
            Self::AdventureGame => "AdventureGame",
            Self::ArcadeGame => "ArcadeGame",
            Self::BoardGame => "BoardGame",
            Self::CardGame => "CardGame",
            Self::LogicGame => "LogicGame",
            Self::RolePlaying => "RolePlaying",
            Self::Shooter => "Shooter",
            Self::Simulation => "Simulation",
            Self::SportsGame => "SportsGame",
            Self::StrategyGame => "StrategyGame",
            Self::Emulator => "Emulator",
            Self::Photography => "Photography",
            Self::RasterGraphics => "RasterGraphics",
            Self::VectorGraphics => "VectorGraphics",
            Self::ThreeDGraphics => "3DGraphics",
            Self::Audio => "Audio",
            Self::Video => "Video",
            Self::AudioVideoEditing => "AudioVideoEditing",
            Self::Player => "Player",
            Self::Recorder => "Recorder",
            Self::WebBrowser => "WebBrowser",
            Self::Email => "Email",
            Self::Chat => "Chat",
            Self::FileTransfer => "FileTransfer",
            Self::Spreadsheet => "Spreadsheet",
            Self::WordProcessor => "WordProcessor",
            Self::Presentation => "Presentation",
            Self::Calendar => "Calendar",
            Self::Finance => "Finance",
            Self::Ide => "IDE",
            Self::TextEditor => "TextEditor",
            Self::Debugger => "Debugger",
            Self::Database => "Database",
            Self::WebDevelopment => "WebDevelopment",
            Self::Math => "Math",
            Self::Languages => "Languages",
            Self::Geography => "Geography",
            Self::Astronomy => "Astronomy",
            Self::FileManager => "FileManager",
            Self::Archiving => "Archiving",
            Self::Security => "Security",
            Self::Monitor => "Monitor",
        }
    }
}
